server:
  port: 7075
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka/
spring:
  application:
    name: client2-service
    # 链路追踪
  zipkin:
    base-url: http://localhost:9411