server:
  port: 7072

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true              #是否与服务注册于发现组件进行结合,设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
          lowerCaseServiceId: true   #该配置开启后，服务名可以小写
      routes:
        - id: client-service
          uri: lb://CLIENT-SERVICE     #lb:从eureka中获取服务
          predicates:
            - Path=/provider/**
          filters:
            - StripPrefix=1

            #          spring.cloud.gateway.discovery.locator.lowerCaseServiceId:true 配置这个可以小写
logging:
  level:
    org.springframework.cloud.gateway: debug

    #      routes:
    #        - id: default_path_to_http
    #          uri: https://windmt.com
    #          order: 10000
    #          predicates:
    #            - Path=/**
    #          filters:
    #            - SetPath=/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka